[package]
name = "qwikmark"
version = "0.2.0"
edition = "2021"
default-run = "qmast"

[dependencies]
nom = "7.1.3"
phf = { version = "0.11.2", features = ["macros"] }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "parse"
harness = false

[profile.bench]
debug = true
